/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controller;

import Services.addCustomer;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import hotel.UserDao;
import javax.swing.table.DefaultTableModel;
import java.lang.String;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static org.joda.time.format.ISODateTimeFormat.date;
import services.roomServices;

/**
 *
 * @author REGIE
 */
public class BookingFrame extends javax.swing.JFrame {
   
    addCustomer ac = new addCustomer();
        UserDao userdao = new UserDao();
    
    private addCustomer adc;
    private PreparedStatement ps;
            
    public BookingFrame() {
        initComponents();
        adc = new addCustomer();
        populatedTable();
    }
    
     public void populatedTable(){
       DefaultTableModel model = (DefaultTableModel) BookingList.getModel();
       adc.populateTable(model);
      
    }
     
     private void displayToTextField(int row){
    DefaultTableModel model = (DefaultTableModel) BookingList.getModel();
    
    RoomCB.setSelectedItem((Object) BookingList.getModel().getValueAt(row, 1));
    CustomerTb.setText(BookingList.getModel().getValueAt(row, 2)+"");
         try {
            row = BookingList.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(row,3));
            BDate.setDate(date);
         } catch (Exception e) {
             
         }

    DurationCB.setSelectedItem((Object) BookingList.getModel().getValueAt(row, 4));
    CostTb.setText(BookingList.getModel().getValueAt(row, 5)+"");
    

    
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RoomCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookingList = new javax.swing.JTable();
        AddBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        DurationCB = new javax.swing.JComboBox<>();
        BDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        CostTb = new javax.swing.JTextField();
        CustomerTb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Room");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 135, 71, -1));

        jLabel4.setText("Customer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 223, 71, -1));

        jLabel5.setText("Booking Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 314, 95, -1));

        jLabel6.setText("Duration in Days");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 386, 117, -1));

        RoomCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        RoomCB.setSelectedIndex(-1);
        jPanel1.add(RoomCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 178, 34));

        BookingList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Room", "Customer", "Date", "Duration", "Cost"
            }
        ));
        BookingList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BookingList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 121, 830, 540));

        AddBtn.setText("ADD");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 70, -1));

        EditBtn.setText("EDIT");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        jPanel1.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 72, -1));

        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, 23));

        DurationCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        DurationCB.setSelectedIndex(-1);
        jPanel1.add(DurationCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 178, 34));
        jPanel1.add(BDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 178, -1));

        jLabel7.setText("Cost");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 448, 117, -1));

        CostTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostTbActionPerformed(evt);
            }
        });
        jPanel1.add(CostTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 178, -1));

        CustomerTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerTbActionPerformed(evt);
            }
        });
        jPanel1.add(CustomerTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 178, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("ROOM'S BOOKING");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 350, 80));

        jLabel10.setFont(new java.awt.Font("Casablanca Noir Personal Use", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Hotel Management System");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 420, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NASAAAAAAAAAAAAAAD.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CostTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostTbActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
       
        
        int Customer = Integer.parseInt(CustomerTb.getText());
        int Cost = Integer.parseInt(CostTb.getText());
        
         
         userdao.setRoom(RoomCB.getSelectedItem());
         userdao.setCustomer(Customer);
         userdao.setDays(DurationCB.getSelectedItem());
         userdao.setCost(Cost);
         
         //Jdate Calendar
         Date date = BDate.getDate();
         SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
         String formatDate = formatter.format(date);
         java.sql.Date sqlDate = java.sql.Date.valueOf(formatDate);
        
         userdao.setDate(sqlDate);
         
        ac.BookingFrame(userdao);
        populatedTable();

         
     
         
         
    }//GEN-LAST:event_AddBtnActionPerformed

    private void CustomerTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerTbActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        
        int Customer = Integer.parseInt(CustomerTb.getText());
        int Cost = Integer.parseInt(CostTb.getText());
        
         
         userdao.setRoom(RoomCB.getSelectedItem().toString());
         userdao.setCustomer(Customer);
         userdao.setDays(DurationCB.getSelectedItem().toString());
         userdao.setCost(Cost);
         
         
         //Jdate Calendar
         Date date = BDate.getDate();
         SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
         String formatDate = formatter.format(date);
         java.sql.Date sqlDate = java.sql.Date.valueOf(formatDate);
        
         userdao.setDate(sqlDate);
         
        ac.updateBooking(userdao);
//        userdao.setRoom(RoomCB.getSelectedItem());
//    userdao.setCustomer(Customer);
//    userdao.setDays(DurationCB.getSelectedItem());
//    userdao.setCost(Cost);
//    userdao.setDate(BDate.getDate());
//
//    ac.updateBooking(userdao);
        populatedTable();
        
    }//GEN-LAST:event_EditBtnActionPerformed

    private void BookingListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingListMouseClicked
       UserDao userdao = new UserDao();
       int row = BookingList.getSelectedRow();
       displayToTextField(row);
       
       EditBtn.setEnabled(true);
       DeleteBtn.setEnabled(true);
       AddBtn.setEnabled(false);
    }//GEN-LAST:event_BookingListMouseClicked

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        
        int row  = BookingList.getSelectedRow();
        int selectedId = (int) BookingList.getModel().getValueAt(row, 0);
        try {
            ac.deleteroom(selectedId);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(roomServices.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        populatedTable();
        emptyField();
    }//GEN-LAST:event_DeleteBtnActionPerformed
    private void emptyField()
    {
         AddBtn.setEnabled(true);
        EditBtn.setEnabled(false);
        DeleteBtn.setEnabled(false);
        UserDao userdao = new UserDao();
        
        userdao = new UserDao();
        
        CustomerTb.setText("");
        Date date = BDate.getDate();
         SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
         String formatDate = formatter.format(BDate.getDate());
         java.sql.Date sqlDate = java.sql.Date.valueOf(formatDate);
         userdao.setDate(sqlDate);
        BDate.setDate(date);
        
        RoomCB.setSelectedItem("");
        DurationCB.setSelectedItem("");
        CostTb.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private com.toedter.calendar.JDateChooser BDate;
    private javax.swing.JTable BookingList;
    private javax.swing.JTextField CostTb;
    private javax.swing.JTextField CustomerTb;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JComboBox<String> DurationCB;
    private javax.swing.JButton EditBtn;
    private javax.swing.JComboBox<String> RoomCB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
